app = "server-billowing-bird-4582"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
PORT = "9000"

[[services]]
  internal_port = 9000
  protocol = "tcp"
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 9000
    handlers = ["proxy_proto"]
